
# # #### 全局 (Values) 变量配置 ####
# apiVersion: 暂未使用
# string
apiVersion: ""
# kind: 暂未使用
# string
kind: ""
# name: Chart 名称
# string
name: ""
# fullname: Chart 完整名称，会覆盖 name
# string
fullname: ""
# namespace: K8S 命名空间。需要符合 RFC1123 规则
# string
# - 参考: https://kubernetes.io/zh-cn/docs/concepts/overview/working-with-objects/names/#dns-label-names
namespace: ""
# annotations: 注释
# map
# - 特殊变量 validOnly 如果定义，不会出现在结果集中。非全局变量配置时生效（此处不生效）
annotations: {}
# labels: 标签
# map
labels: {}
# helmLabels: 是否在 labels 中注入内置的与 HELM 相关的标签
# bool
helmLabels: false
# helmTesting: 是否允许生成 YAML 文件，不建议在非开发环境使用
# bool
helmTesting: false
# enable: 是否允许生成 YAML 文件，建议在正式环境使用
# bool
enable: false
# #### 全局变量 ####

# # #### 上下文 (Context) 变量配置，可继承、覆盖全局 (Values) 变量 ####
# # 参考 examples/values 目录中的 YAML 配置
