
TkeServiceConfig:
  # protocol 相同会进行合并
  # slice, map
  l4Listeners:
  - protocol: TCP # 协议端口锚定Service的四层规则。必填，枚举值：TCP|UDP。
    port: 80 # 必填，可选值：1~65535。
    deregisterTargetRst: true # 选填，布尔值。双向 RST 开关。
    session: # 会话保持相关配置。选填
      enable: true # 是否开启会话保持。必填，布尔值
      sessionExpireTime: 100 # 会话保持的时间。选填，默认值：30，可选值：30~3600，单位：秒。
    healthCheck: # 健康检查相关配置。选填
      enable: true # 是否开启会话保持。必填，布尔值
      intervalTime: 10 # 健康检查探测间隔时间。选填，默认值：5，可选值：5~300，单位：秒。
      healthNum: 2 # 健康阈值，表示当连续探测几次健康则表示该转发正常。选填，默认值：3，可选值：2~10，单位：次。
      unHealthNum: 3 # 不健康阈值，表示当连续探测几次健康则表示该转发异常。选填，默认值：3，可选值：2~10，单位：次。
      timeout: 10 # 健康检查的响应超时时间，响应超时时间要小于检查间隔时间。选填，默认值：2，可选值：2~60，单位：秒。
    scheduler: WRR # 请求转发方式配置。WRR、LEAST_CONN 分别表示按权重轮询、最小连接数。选填，枚举值：WRR|LEAST_CONN。
  # protocol 相同会进行合并
  # slice, map
  l7Listeners:
  - protocol: HTTP
    port: 80
    domains:
    - domain: ""     # domain为空表示使用VIP作为域名
      rules:
      - url: "/health"
        forwardType: HTTP # 指定后端协议为 HTTP
        healthCheck:
          enable: false
  - protocol: HTTPS
    port: 443
    defaultServer: "sample.tencent.com" # 默认域名
    keepaliveEnable: 1                  # 监听器开启长连接（非keepalive白名单用户，请勿声明该字段）
    domains:
    - domain: "sample.tencent.com"
      rules:
      - url: "/"
        forwardType: HTTPS # 指定后端协议为 HTTPS
        session:
          enable: true
          sessionExpireTime: 3600
        healthCheck:
          enable: true
          intervalTime: 10 # intervalTime 要大于 timeout，否则会出错
          timeout: 5 # timeout 要小于 intervalTime，否则会出错
          healthNum: 2
          unHealthNum: 2
          httpCheckPath: "/checkHealth"
          httpCheckDomain: "sample.tencent.com" #注意：健康检查必须使用固定域名进行探测，如果您在.spec.loadBalancer.l7Listeners.protocol.domains.domain 里填写的是泛域名，一定要使用 httpCheckDomain 字段明确具体需要健康检查的域名，否则泛域名不支持健康检查。
          httpCheckMethod: HEAD
          httpCode: 31 # 可选值：1~31，默认 31。 1 表示探测后返回值 1xx 代表健康，2 表示返回 2xx 代表健康，4 表示返回 3xx 代表健康，8 表示返回 4xx 代表健康，16 表示返回 5xx 代表健康。若希望多种返回码都可代表健康，则将相应的值相加。
          sourceIpType: 0 # 可选值：0或1，默认0。设定健康检查源ip，0 表示负载均衡VIP，1 表示 100.64.0.0/10 网段ip
        scheduler: WRR
