
StatefulSet:
  helmTesting: true
  helmLabels: false
  namespace: xxx
  nameAlias: name-alias
  annotations:
    validOnly: true
    app.example.com: 123
  labels:
    name: ccc
  minReadySeconds: 10
  revisionHistoryLimit: 10
  # matchExpressions
  selector:
    # slice
  - matchExpressions:
    # - podAntiAffinity1 = 111
    - xxx in (vvv, fff)
    # map
  - matchLabels:
     podAntiAffinity2: 222
  activeDeadlineSeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 1
  start: 0
  ordinals: 10
  volumeClaimTemplates:
    name: vct-name1
    accessModes: ReadWriteOnce
    storageClassName: storage-class-name
    size: 22Gi
    vct-name1:
      accessModes: ReadWriteOnce, ReadOnlyMany
      storageClassName: storage-class-name
      size: 2Gi
    vct-name2:
      accessModes:
      - ReadWriteOnce
      storageClassName: storage-class-name
      storage: 2Gi
volumeClaimTemplates:
- name: vct-name1
  accessModes: ReadWriteOnce
  storageClassName: storage-class-name
  size: 12Gi
- vct-name2:
    accessModes:
    - ReadWriteOnce
    storageClassName: storage-class-name
    storage: 12Gi
ordinals:
  start: 100
strategy:
  type: RollingUpdate
selector:
  matchExpressions:
  - podAntiAffinity3 = 333
  matchLabels:
    podAntiAffinity4: 444
