
Secret:
  helmTesting: true
  helmLabels: false
  namespace: xxx
  nameAlias: name-alias
  annotations:
    validOnly: true
    app.example.com: 123
  labels:
    name: ccc
  immutable: true
  type:
  data:
    a: 123
  dataFiles:
    - ce: config/envs.yaml
  stringData:
    b: 123
  stringDataFiles:
    stringDataxx: config/envs.yaml
stringData:
- cc: xxx
stringDataFiles:
- config/envs.yaml
